config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "reservations#index"

  resources :reservations, only: [:index, :create_or_update] do
    collection do
      put :create_or_update
    end
  end

  namespace :admin do
    resources :room_lock_pin_codes, only: [:reset, :resend] do
      member do
        put :resend
        put :reset
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :reservations, inverse_of: :guest
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room, inverse_of: :reservations
  belongs_to :guest, inverse_of: :reservations
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations, inverse_of: :room
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_action :check_admin

    private

    def check_admin
      unless current_user.admin?
        redirect_to root_path, alert: 'You have to be logged in as admin to see this page.'
      end
    end
  end
end

app/controllers/admin/room_lock_pin_codes_controller.rb
module Admin
  class RoomLockPinCodesController < Admin::AdminController
    def resend
      if SendRoomPinCode.call(params[:id].to_i)
        redirect_to root_path, alert: 'Lock code has been successfully resent to guest.'
      end
    end

    def reset
      if SetRoomPinCode.call(params[:id].to_i)
        message = 'New pin code has been set!'
      else
        message = 'New pin code has not been set! Something went wrong.'
      end

      redirect_to root_path, alert: message
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create_or_update

  def index
    @q = Reservation.ransack(params[:q])
    @reservations = @q.result.includes(:room, :guest)
  end

  def create_or_update
    status = params[:status]
    if status == 'created'
      ImportReservations.call(reservation: reservation_roomy_id)
    elsif status == 'cancelled'
      CancelReservation.call(reservation_roomy_id)
    end

    render json: {}, status: :ok
  end

  private

  def reservation_roomy_id
    @reservation_roomy_id ||= params[:reservation_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LockCodesManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :guest_first_name_eq %>
  <%= f.search_field :guest_first_name_eq %>

  <%= f.label :guest_last_name_eq %>
  <%= f.search_field :guest_last_name_eq %>

  <%= f.submit %>
<% end %>

<br>
<br>

<table id="reservations" border="1" cellpadding="0" cellspacing="0" width="1400px">
  <thead>
  <tr>
    <th>Reservation id</th>
    <th>Reservation cancelled</th>
    <th>Guest first name</th>
    <th>Guest last name</th>
    <th>Room number</th>
    <th>Room code</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.id %></td>
      <td><%= reservation.cancelled %></td>
      <td><%= reservation.guest.first_name %></td>
      <td><%= reservation.guest.last_name %></td>
      <td><%= reservation.room.number %></td>
      <td><%= reservation.room_lock_pin_code %></td>
      <td>
        <% if current_user.admin? %>
          <% if reservation.room.lock_uuid.present? %>
            <% if reservation.room_lock_pin_code.present? %>
              <%= button_to 'Resend code', resend_admin_room_lock_pin_code_path(reservation.id), method: :put %>
            <% end %>
            <%= button_to 'Reset code', reset_admin_room_lock_pin_code_path(reservation.id), method: :put %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>